In [5]:
import numpy as np

In [2]:
F=[1,2,3,4,5]
F

[1, 2, 3, 4, 5]

In [6]:
a=np.array([1,2,3,4,5])
print(a)
b=np.array([[1,2,3,5,4],[7,8,9,6,7]])
print(b)
c=np.array([[[1,2,3,4,5],[2,5,7,4,0],[1,3,5,7,9]]])
print(c)

[1 2 3 4 5]
[[1 2 3 5 4]
 [7 8 9 6 7]]
[[[1 2 3 4 5]
  [2 5 7 4 0]
  [1 3 5 7 9]]]


In [7]:
type(a)

numpy.ndarray

In [8]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [9]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [10]:
print(a.dtype)

int64


In [11]:
c.transpose()

array([[[1],
        [2],
        [1]],

       [[2],
        [5],
        [3]],

       [[3],
        [7],
        [5]],

       [[4],
        [4],
        [7]],

       [[5],
        [0],
        [9]]])

In [12]:
#np.empty((4,4),dtype=int)


In [15]:
np.empty((4,4),dtype=float)


array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.69118787e-306],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
        6.23057349e-307],
       [1.42419530e-306, 2.22522597e-306, 1.33512173e-306,
        9.45737027e-308],
       [1.22383561e-307, 1.33508506e-307, 9.45703923e-308,
        8.34425615e-308]])

In [16]:
x=np.ones(6)

In [17]:
x

array([1., 1., 1., 1., 1., 1.])

In [20]:
y=np.zeros((4,4))

In [21]:
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
a=np.arange(1,20)

In [24]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [27]:
a=np.arange(3,25,3)
a

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [28]:
#reshape

In [35]:
z=np.arange(1,10)

z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
data=z.reshape((3,3))

In [37]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
p=np.arange(1,100,2)

p

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [43]:
p.reshape((1,-1))

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
        33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63,
        65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95,
        97, 99]])

In [44]:
p.flatten()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [45]:
a.ravel()

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [46]:
#slicing

In [56]:
a=np.arange(1,51)
a=a.reshape((10,5))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [58]:
a[0]

array([1, 2, 3, 4, 5])

In [59]:
a[0,0]

np.int64(1)

In [60]:
a[3,4]

np.int64(20)

In [61]:
a[2:6]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [62]:
a[::]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [63]:
a[:10]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [64]:
a[:,3]

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49])

In [66]:
a[1:3,4]

array([10, 15])

In [67]:
a[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [68]:
a[:,2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [69]:
a=np.arange(0,18).reshape(6,3)

In [70]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [71]:
b=np.arange(20,38).reshape(6,3)
b

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

In [72]:
a+b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [73]:
a*b

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [74]:
a/b

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [75]:
b/a

C:\Users\Yash\AppData\Local\Temp\ipykernel_14356\2243761560.py:1: RuntimeWarning: divide by zero encountered in divide
  b/a


array([[        inf, 21.        , 11.        ],
       [ 7.66666667,  6.        ,  5.        ],
       [ 4.33333333,  3.85714286,  3.5       ],
       [ 3.22222222,  3.        ,  2.81818182],
       [ 2.66666667,  2.53846154,  2.42857143],
       [ 2.33333333,  2.25      ,  2.17647059]])

In [76]:
a-b

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [77]:
b-a

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [78]:
b*a

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [79]:
a.shape

(6, 3)

In [80]:
b.shape

(6, 3)

In [81]:
a@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 3)

In [86]:
b=b.reshape((3,6))


In [87]:
a@b

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [88]:
a.dot(b)

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [89]:
b.max()

np.int64(37)

In [90]:
b.min()

np.int64(20)

In [91]:
np.sum(a)

np.int64(153)